import React from 'react';
import { Link } from 'react-router-dom';
import SEO from '../components/SEO';

const questions = [
  ['Provider workflow', 'List the workflows your team needs in one system: participant records, care plans, rostering, mobile documentation, billing, payroll and reporting.'],
  ['Workforce model', 'Test how each product handles administrators, coordinators, permanent workers and casual or relief workers as your team changes.'],
  ['Billing controls', 'Ask how service delivery is reviewed before invoicing, how pricing arrangements are maintained, and what your team must approve before a claim is submitted.'],
  ['Documentation quality', 'Review how progress notes are created, checked and retained. Kinly describes Guardian AI as a staff-reviewed progress-note QA tool, not a clinical decision-maker.'],
  ['Implementation', 'Request a documented migration plan covering data exports, validation, training, parallel running and ownership of cutover tasks.'],
  ['Security and support', 'Confirm current hosting, permissions, audit logs, support hours, incident processes and any integrations that matter to your provider.'],
];

export default function ShiftCareComparisonPage() {
 return <>
  <SEO title="Kinly CarePro vs ShiftCare: NDIS Provider Software Compared" description="Compare Kinly CarePro and ShiftCare using practical questions about NDIS provider workflows, rostering, participant management, implementation and support." url="/vs/shiftcare" breadcrumbs={[{name:'Compare software',path:'/compare'},{name:'Kinly CarePro vs ShiftCare',path:'/vs/shiftcare'}]} />
  <section className="pt-32 pb-20 bg-gradient-to-b from-[#f2fbff] via-white to-white"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
   <p className="text-primary font-bold uppercase tracking-widest text-xs">NDIS software comparison</p><h1 className="mt-3 text-4xl md:text-6xl font-extrabold tracking-tight text-slate-900">Kinly CarePro vs ShiftCare</h1>
   <p className="mt-6 text-xl text-slate-600 leading-relaxed max-w-3xl">Both products should be assessed against your provider’s service model. Kinly CarePro is built around connected participant operations, rostering, documentation and billing workflows for Australian disability-service providers.</p>
   <div className="mt-8 flex flex-wrap gap-4"><Link to="/contact#book-demo" className="bg-primary text-white font-bold px-7 py-3 rounded-xl">Book a Kinly demo</Link><Link to="/pricing" className="border border-slate-300 font-bold px-7 py-3 rounded-xl">View Kinly pricing</Link></div>
  </div></section>
  <section className="py-16"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold">Short answer: which may suit your provider?</h2><p className="mt-5 max-w-4xl text-slate-600 leading-relaxed">Kinly CarePro may suit providers seeking participant-based pricing, unlimited staff accounts and an all-in-one workflow that includes Guardian AI progress-note QA and deterministic billing tooling. Whether it is the right choice depends on the capabilities, implementation approach, integrations and commercial terms you need. Review ShiftCare’s current product information directly, then ask both vendors to demonstrate your priority workflows.</p>
  <div className="grid md:grid-cols-2 gap-5 mt-10"><div className="rounded-2xl p-7 bg-primary/5 border border-primary/20"><h3 className="font-bold text-xl">Kinly CarePro pricing approach</h3><p className="mt-3 text-slate-700 leading-relaxed">Kinly advertises $25 AUD per active participant per month with unlimited staff accounts. Confirm inclusions, billing basis and contract terms with Kinly before purchasing.</p></div><div className="rounded-2xl p-7 bg-slate-50 border border-slate-200"><h3 className="font-bold text-xl">A fair comparison</h3><p className="mt-3 text-slate-700 leading-relaxed">Vendor features and pricing change. This page intentionally does not make unverified claims about ShiftCare’s current features, pricing or service terms.</p></div></div></div></section>
  <section className="py-16 bg-slate-50"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold">Feature comparison: what to verify in a demo</h2><div className="grid md:grid-cols-2 gap-5 mt-8">{questions.map(([title,copy])=><article key={title} className="bg-white rounded-2xl border border-slate-200 p-6"><h3 className="font-bold text-lg">{title}</h3><p className="mt-3 text-slate-600 leading-relaxed">{copy}</p></article>)}</div></div></section>
  <section className="py-16"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 grid md:grid-cols-2 gap-12"><div><h2 className="text-3xl font-bold">Migration considerations</h2><p className="mt-5 text-slate-600 leading-relaxed">A successful system change starts with a clear data inventory. Identify participant records, care plans, service agreements, rosters, notes, staff records and reporting history. Agree on migration responsibilities, test a representative sample, train your users and set a go-live support plan.</p><p className="mt-4 text-slate-600 leading-relaxed">Ask Kinly about its onboarding process for your specific data and operational needs. Do not assume a migration is downtime-free without a written, mutually agreed plan.</p></div><div><h2 className="text-3xl font-bold">Frequently asked questions</h2><h3 className="mt-5 font-bold">Is Guardian AI included in Kinly CarePro?</h3><p className="mt-2 text-slate-600">Kinly presents Guardian AI as part of its progress-note quality-assurance workflow. Staff review and approve suggestions and remain responsible for documentation.</p><h3 className="mt-5 font-bold">Does billing software guarantee compliant claims?</h3><p className="mt-2 text-slate-600">No. Providers must review their billing and meet applicable NDIA requirements. Confirm the current PAPL coverage and your responsibilities before relying on any product.</p></div></div></section>
  <section className="py-12 bg-slate-950 text-white"><div className="max-w-5xl mx-auto px-4"><h2 className="text-3xl font-bold">See Kinly CarePro in your workflow</h2><p className="mt-3 text-slate-300">Bring your real roster, documentation and billing questions to a product demonstration.</p><Link to="/contact#book-demo" className="inline-block mt-6 bg-emerald-400 text-slate-950 px-7 py-3 rounded-xl font-bold">Book a demo</Link><p className="mt-8 text-xs text-slate-400">ShiftCare is a third-party trademark. Kinly CarePro is independent and is not affiliated with or endorsed by ShiftCare.</p></div></section>
 </>;
}
